Architecture overview diagram
opensearch-project/opensearch-ci pull request #8
Opened 2021-09-23 22:48 UTC by peternied

Signed-off-by: Peter Nied <petern@amazon.com>

### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-09-23 22:49 UTC, peternied commented
See a preview with the 'rich diff' button
![image](https://user-images.githubusercontent.com/2754967/134593894-b068e450-a391-419c-8872-bf9d23d91dad.png)

2021-09-24 15:53 UTC, dblock requested changes

2021-09-24 15:53 UTC, dblock commented on README.md
> +![Architecture Diagram](.\img\opensearch-ci-overview.png)
This doesn't seem to render, need forward slashes?

2021-09-24 15:53 UTC, dblock commented on README.md
> +[Source](https://gist.github.com/peternied/55db1ce5277a61923519364dd6271ce5)
Migrate into this repo.

2021-09-24 22:09 UTC, dblock commented
I would think the generation job would PR the outputs when they change or otherwise maybe GHA is not the right approach here and you want some kind of precommit hook to update the SVGs?

2021-09-24 22:11 UTC, dblock approved these changes

2021-09-24 23:02 UTC, merged